// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resources/protobuf/user.proto

// Protobuf Java Version: 3.25.1
package com.java.springboot.entities.protobuf;

public final class ProtocolBufferWrapper {
  private ProtocolBufferWrapper() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UsersOrBuilder extends
      // @@protoc_insertion_point(interface_extends:springboot.Users)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .springboot.User user = 1;</code>
     */
    java.util.List<com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User> 
        getUserList();
    /**
     * <code>repeated .springboot.User user = 1;</code>
     */
    com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User getUser(int index);
    /**
     * <code>repeated .springboot.User user = 1;</code>
     */
    int getUserCount();
    /**
     * <code>repeated .springboot.User user = 1;</code>
     */
    java.util.List<? extends com.java.springboot.entities.protobuf.ProtocolBufferWrapper.UserOrBuilder> 
        getUserOrBuilderList();
    /**
     * <code>repeated .springboot.User user = 1;</code>
     */
    com.java.springboot.entities.protobuf.ProtocolBufferWrapper.UserOrBuilder getUserOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code springboot.Users}
   */
  public static final class Users extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:springboot.Users)
      UsersOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Users.newBuilder() to construct.
    private Users(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Users() {
      user_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Users();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.java.springboot.entities.protobuf.ProtocolBufferWrapper.internal_static_springboot_Users_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.java.springboot.entities.protobuf.ProtocolBufferWrapper.internal_static_springboot_Users_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users.class, com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users.Builder.class);
    }

    public static final int USER_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private java.util.List<com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User> user_;
    /**
     * <code>repeated .springboot.User user = 1;</code>
     */
    @java.lang.Override
    public java.util.List<com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User> getUserList() {
      return user_;
    }
    /**
     * <code>repeated .springboot.User user = 1;</code>
     */
    @java.lang.Override
    public java.util.List<? extends com.java.springboot.entities.protobuf.ProtocolBufferWrapper.UserOrBuilder> 
        getUserOrBuilderList() {
      return user_;
    }
    /**
     * <code>repeated .springboot.User user = 1;</code>
     */
    @java.lang.Override
    public int getUserCount() {
      return user_.size();
    }
    /**
     * <code>repeated .springboot.User user = 1;</code>
     */
    @java.lang.Override
    public com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User getUser(int index) {
      return user_.get(index);
    }
    /**
     * <code>repeated .springboot.User user = 1;</code>
     */
    @java.lang.Override
    public com.java.springboot.entities.protobuf.ProtocolBufferWrapper.UserOrBuilder getUserOrBuilder(
        int index) {
      return user_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < user_.size(); i++) {
        output.writeMessage(1, user_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < user_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, user_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users)) {
        return super.equals(obj);
      }
      com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users other = (com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users) obj;

      if (!getUserList()
          .equals(other.getUserList())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getUserCount() > 0) {
        hash = (37 * hash) + USER_FIELD_NUMBER;
        hash = (53 * hash) + getUserList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code springboot.Users}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:springboot.Users)
        com.java.springboot.entities.protobuf.ProtocolBufferWrapper.UsersOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.java.springboot.entities.protobuf.ProtocolBufferWrapper.internal_static_springboot_Users_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.java.springboot.entities.protobuf.ProtocolBufferWrapper.internal_static_springboot_Users_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users.class, com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users.Builder.class);
      }

      // Construct using com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        if (userBuilder_ == null) {
          user_ = java.util.Collections.emptyList();
        } else {
          user_ = null;
          userBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.java.springboot.entities.protobuf.ProtocolBufferWrapper.internal_static_springboot_Users_descriptor;
      }

      @java.lang.Override
      public com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users getDefaultInstanceForType() {
        return com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users.getDefaultInstance();
      }

      @java.lang.Override
      public com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users build() {
        com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users buildPartial() {
        com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users result = new com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users(this);
        buildPartialRepeatedFields(result);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartialRepeatedFields(com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users result) {
        if (userBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            user_ = java.util.Collections.unmodifiableList(user_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.user_ = user_;
        } else {
          result.user_ = userBuilder_.build();
        }
      }

      private void buildPartial0(com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users result) {
        int from_bitField0_ = bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users) {
          return mergeFrom((com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users other) {
        if (other == com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users.getDefaultInstance()) return this;
        if (userBuilder_ == null) {
          if (!other.user_.isEmpty()) {
            if (user_.isEmpty()) {
              user_ = other.user_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureUserIsMutable();
              user_.addAll(other.user_);
            }
            onChanged();
          }
        } else {
          if (!other.user_.isEmpty()) {
            if (userBuilder_.isEmpty()) {
              userBuilder_.dispose();
              userBuilder_ = null;
              user_ = other.user_;
              bitField0_ = (bitField0_ & ~0x00000001);
              userBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getUserFieldBuilder() : null;
            } else {
              userBuilder_.addAllMessages(other.user_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User m =
                    input.readMessage(
                        com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User.parser(),
                        extensionRegistry);
                if (userBuilder_ == null) {
                  ensureUserIsMutable();
                  user_.add(m);
                } else {
                  userBuilder_.addMessage(m);
                }
                break;
              } // case 10
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.util.List<com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User> user_ =
        java.util.Collections.emptyList();
      private void ensureUserIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          user_ = new java.util.ArrayList<com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User>(user_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User, com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User.Builder, com.java.springboot.entities.protobuf.ProtocolBufferWrapper.UserOrBuilder> userBuilder_;

      /**
       * <code>repeated .springboot.User user = 1;</code>
       */
      public java.util.List<com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User> getUserList() {
        if (userBuilder_ == null) {
          return java.util.Collections.unmodifiableList(user_);
        } else {
          return userBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .springboot.User user = 1;</code>
       */
      public int getUserCount() {
        if (userBuilder_ == null) {
          return user_.size();
        } else {
          return userBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .springboot.User user = 1;</code>
       */
      public com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User getUser(int index) {
        if (userBuilder_ == null) {
          return user_.get(index);
        } else {
          return userBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .springboot.User user = 1;</code>
       */
      public Builder setUser(
          int index, com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserIsMutable();
          user_.set(index, value);
          onChanged();
        } else {
          userBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .springboot.User user = 1;</code>
       */
      public Builder setUser(
          int index, com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.set(index, builderForValue.build());
          onChanged();
        } else {
          userBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .springboot.User user = 1;</code>
       */
      public Builder addUser(com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserIsMutable();
          user_.add(value);
          onChanged();
        } else {
          userBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .springboot.User user = 1;</code>
       */
      public Builder addUser(
          int index, com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User value) {
        if (userBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureUserIsMutable();
          user_.add(index, value);
          onChanged();
        } else {
          userBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .springboot.User user = 1;</code>
       */
      public Builder addUser(
          com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.add(builderForValue.build());
          onChanged();
        } else {
          userBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .springboot.User user = 1;</code>
       */
      public Builder addUser(
          int index, com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User.Builder builderForValue) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.add(index, builderForValue.build());
          onChanged();
        } else {
          userBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .springboot.User user = 1;</code>
       */
      public Builder addAllUser(
          java.lang.Iterable<? extends com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User> values) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, user_);
          onChanged();
        } else {
          userBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .springboot.User user = 1;</code>
       */
      public Builder clearUser() {
        if (userBuilder_ == null) {
          user_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          userBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .springboot.User user = 1;</code>
       */
      public Builder removeUser(int index) {
        if (userBuilder_ == null) {
          ensureUserIsMutable();
          user_.remove(index);
          onChanged();
        } else {
          userBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .springboot.User user = 1;</code>
       */
      public com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User.Builder getUserBuilder(
          int index) {
        return getUserFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .springboot.User user = 1;</code>
       */
      public com.java.springboot.entities.protobuf.ProtocolBufferWrapper.UserOrBuilder getUserOrBuilder(
          int index) {
        if (userBuilder_ == null) {
          return user_.get(index);  } else {
          return userBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .springboot.User user = 1;</code>
       */
      public java.util.List<? extends com.java.springboot.entities.protobuf.ProtocolBufferWrapper.UserOrBuilder> 
           getUserOrBuilderList() {
        if (userBuilder_ != null) {
          return userBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(user_);
        }
      }
      /**
       * <code>repeated .springboot.User user = 1;</code>
       */
      public com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User.Builder addUserBuilder() {
        return getUserFieldBuilder().addBuilder(
            com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User.getDefaultInstance());
      }
      /**
       * <code>repeated .springboot.User user = 1;</code>
       */
      public com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User.Builder addUserBuilder(
          int index) {
        return getUserFieldBuilder().addBuilder(
            index, com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User.getDefaultInstance());
      }
      /**
       * <code>repeated .springboot.User user = 1;</code>
       */
      public java.util.List<com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User.Builder> 
           getUserBuilderList() {
        return getUserFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User, com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User.Builder, com.java.springboot.entities.protobuf.ProtocolBufferWrapper.UserOrBuilder> 
          getUserFieldBuilder() {
        if (userBuilder_ == null) {
          userBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User, com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User.Builder, com.java.springboot.entities.protobuf.ProtocolBufferWrapper.UserOrBuilder>(
                  user_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          user_ = null;
        }
        return userBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:springboot.Users)
    }

    // @@protoc_insertion_point(class_scope:springboot.Users)
    private static final com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users();
    }

    public static com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Users>
        PARSER = new com.google.protobuf.AbstractParser<Users>() {
      @java.lang.Override
      public Users parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Users> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Users> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.java.springboot.entities.protobuf.ProtocolBufferWrapper.Users getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:springboot.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string userName = 3;</code>
     * @return The userName.
     */
    java.lang.String getUserName();
    /**
     * <code>string userName = 3;</code>
     * @return The bytes for userName.
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>string city = 4;</code>
     * @return The city.
     */
    java.lang.String getCity();
    /**
     * <code>string city = 4;</code>
     * @return The bytes for city.
     */
    com.google.protobuf.ByteString
        getCityBytes();

    /**
     * <code>string description = 5;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 5;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>string dateOfJoining = 6;</code>
     * @return The dateOfJoining.
     */
    java.lang.String getDateOfJoining();
    /**
     * <code>string dateOfJoining = 6;</code>
     * @return The bytes for dateOfJoining.
     */
    com.google.protobuf.ByteString
        getDateOfJoiningBytes();

    /**
     * <code>string exactDob = 7;</code>
     * @return The exactDob.
     */
    java.lang.String getExactDob();
    /**
     * <code>string exactDob = 7;</code>
     * @return The bytes for exactDob.
     */
    com.google.protobuf.ByteString
        getExactDobBytes();

    /**
     * <code>int32 status = 8;</code>
     * @return The status.
     */
    int getStatus();
  }
  /**
   * Protobuf type {@code springboot.User}
   */
  public static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:springboot.User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      name_ = "";
      userName_ = "";
      city_ = "";
      description_ = "";
      dateOfJoining_ = "";
      exactDob_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new User();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.java.springboot.entities.protobuf.ProtocolBufferWrapper.internal_static_springboot_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.java.springboot.entities.protobuf.ProtocolBufferWrapper.internal_static_springboot_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User.class, com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_ = 0;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @java.lang.Override
    public int getId() {
      return id_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERNAME_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object userName_ = "";
    /**
     * <code>string userName = 3;</code>
     * @return The userName.
     */
    @java.lang.Override
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <code>string userName = 3;</code>
     * @return The bytes for userName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITY_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object city_ = "";
    /**
     * <code>string city = 4;</code>
     * @return The city.
     */
    @java.lang.Override
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      }
    }
    /**
     * <code>string city = 4;</code>
     * @return The bytes for city.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object description_ = "";
    /**
     * <code>string description = 5;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 5;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATEOFJOINING_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object dateOfJoining_ = "";
    /**
     * <code>string dateOfJoining = 6;</code>
     * @return The dateOfJoining.
     */
    @java.lang.Override
    public java.lang.String getDateOfJoining() {
      java.lang.Object ref = dateOfJoining_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dateOfJoining_ = s;
        return s;
      }
    }
    /**
     * <code>string dateOfJoining = 6;</code>
     * @return The bytes for dateOfJoining.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDateOfJoiningBytes() {
      java.lang.Object ref = dateOfJoining_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dateOfJoining_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXACTDOB_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private volatile java.lang.Object exactDob_ = "";
    /**
     * <code>string exactDob = 7;</code>
     * @return The exactDob.
     */
    @java.lang.Override
    public java.lang.String getExactDob() {
      java.lang.Object ref = exactDob_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        exactDob_ = s;
        return s;
      }
    }
    /**
     * <code>string exactDob = 7;</code>
     * @return The bytes for exactDob.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getExactDobBytes() {
      java.lang.Object ref = exactDob_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        exactDob_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATUS_FIELD_NUMBER = 8;
    private int status_ = 0;
    /**
     * <code>int32 status = 8;</code>
     * @return The status.
     */
    @java.lang.Override
    public int getStatus() {
      return status_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userName_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(city_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, city_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, description_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dateOfJoining_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, dateOfJoining_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(exactDob_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, exactDob_);
      }
      if (status_ != 0) {
        output.writeInt32(8, status_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(userName_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userName_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(city_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, city_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(description_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, description_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(dateOfJoining_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, dateOfJoining_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(exactDob_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, exactDob_);
      }
      if (status_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(8, status_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User)) {
        return super.equals(obj);
      }
      com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User other = (com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User) obj;

      if (getId()
          != other.getId()) return false;
      if (!getName()
          .equals(other.getName())) return false;
      if (!getUserName()
          .equals(other.getUserName())) return false;
      if (!getCity()
          .equals(other.getCity())) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (!getDateOfJoining()
          .equals(other.getDateOfJoining())) return false;
      if (!getExactDob()
          .equals(other.getExactDob())) return false;
      if (getStatus()
          != other.getStatus()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (37 * hash) + CITY_FIELD_NUMBER;
      hash = (53 * hash) + getCity().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + DATEOFJOINING_FIELD_NUMBER;
      hash = (53 * hash) + getDateOfJoining().hashCode();
      hash = (37 * hash) + EXACTDOB_FIELD_NUMBER;
      hash = (53 * hash) + getExactDob().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code springboot.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:springboot.User)
        com.java.springboot.entities.protobuf.ProtocolBufferWrapper.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.java.springboot.entities.protobuf.ProtocolBufferWrapper.internal_static_springboot_User_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.java.springboot.entities.protobuf.ProtocolBufferWrapper.internal_static_springboot_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User.class, com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User.Builder.class);
      }

      // Construct using com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        id_ = 0;
        name_ = "";
        userName_ = "";
        city_ = "";
        description_ = "";
        dateOfJoining_ = "";
        exactDob_ = "";
        status_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.java.springboot.entities.protobuf.ProtocolBufferWrapper.internal_static_springboot_User_descriptor;
      }

      @java.lang.Override
      public com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User getDefaultInstanceForType() {
        return com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User.getDefaultInstance();
      }

      @java.lang.Override
      public com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User build() {
        com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User buildPartial() {
        com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User result = new com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.id_ = id_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.userName_ = userName_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.city_ = city_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.description_ = description_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.dateOfJoining_ = dateOfJoining_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          result.exactDob_ = exactDob_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          result.status_ = status_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User) {
          return mergeFrom((com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User other) {
        if (other == com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getCity().isEmpty()) {
          city_ = other.city_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getDateOfJoining().isEmpty()) {
          dateOfJoining_ = other.dateOfJoining_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        if (!other.getExactDob().isEmpty()) {
          exactDob_ = other.exactDob_;
          bitField0_ |= 0x00000040;
          onChanged();
        }
        if (other.getStatus() != 0) {
          setStatus(other.getStatus());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                id_ = input.readInt32();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              case 18: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                userName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                city_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                description_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                dateOfJoining_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              case 58: {
                exactDob_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000040;
                break;
              } // case 58
              case 64: {
                status_ = input.readInt32();
                bitField0_ |= 0x00000080;
                break;
              } // case 64
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @java.lang.Override
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {

        id_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <code>string userName = 3;</code>
       * @return The userName.
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string userName = 3;</code>
       * @return The bytes for userName.
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string userName = 3;</code>
       * @param value The userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        userName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string userName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserName() {
        userName_ = getDefaultInstance().getUserName();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string userName = 3;</code>
       * @param value The bytes for userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        userName_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object city_ = "";
      /**
       * <code>string city = 4;</code>
       * @return The city.
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string city = 4;</code>
       * @return The bytes for city.
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string city = 4;</code>
       * @param value The city to set.
       * @return This builder for chaining.
       */
      public Builder setCity(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        city_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string city = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCity() {
        city_ = getDefaultInstance().getCity();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string city = 4;</code>
       * @param value The bytes for city to set.
       * @return This builder for chaining.
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        city_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 5;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 5;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 5;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        description_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        description_ = getDefaultInstance().getDescription();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string description = 5;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        description_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object dateOfJoining_ = "";
      /**
       * <code>string dateOfJoining = 6;</code>
       * @return The dateOfJoining.
       */
      public java.lang.String getDateOfJoining() {
        java.lang.Object ref = dateOfJoining_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dateOfJoining_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dateOfJoining = 6;</code>
       * @return The bytes for dateOfJoining.
       */
      public com.google.protobuf.ByteString
          getDateOfJoiningBytes() {
        java.lang.Object ref = dateOfJoining_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dateOfJoining_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dateOfJoining = 6;</code>
       * @param value The dateOfJoining to set.
       * @return This builder for chaining.
       */
      public Builder setDateOfJoining(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        dateOfJoining_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string dateOfJoining = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearDateOfJoining() {
        dateOfJoining_ = getDefaultInstance().getDateOfJoining();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string dateOfJoining = 6;</code>
       * @param value The bytes for dateOfJoining to set.
       * @return This builder for chaining.
       */
      public Builder setDateOfJoiningBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        dateOfJoining_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private java.lang.Object exactDob_ = "";
      /**
       * <code>string exactDob = 7;</code>
       * @return The exactDob.
       */
      public java.lang.String getExactDob() {
        java.lang.Object ref = exactDob_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          exactDob_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string exactDob = 7;</code>
       * @return The bytes for exactDob.
       */
      public com.google.protobuf.ByteString
          getExactDobBytes() {
        java.lang.Object ref = exactDob_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          exactDob_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string exactDob = 7;</code>
       * @param value The exactDob to set.
       * @return This builder for chaining.
       */
      public Builder setExactDob(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        exactDob_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>string exactDob = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearExactDob() {
        exactDob_ = getDefaultInstance().getExactDob();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      /**
       * <code>string exactDob = 7;</code>
       * @param value The bytes for exactDob to set.
       * @return This builder for chaining.
       */
      public Builder setExactDobBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        exactDob_ = value;
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private int status_ ;
      /**
       * <code>int32 status = 8;</code>
       * @return The status.
       */
      @java.lang.Override
      public int getStatus() {
        return status_;
      }
      /**
       * <code>int32 status = 8;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(int value) {

        status_ = value;
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>int32 status = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000080);
        status_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:springboot.User)
    }

    // @@protoc_insertion_point(class_scope:springboot.User)
    private static final com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User();
    }

    public static com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @java.lang.Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.java.springboot.entities.protobuf.ProtocolBufferWrapper.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_springboot_Users_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_springboot_Users_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_springboot_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_springboot_User_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\035resources/protobuf/user.proto\022\nspringb" +
      "oot\"\'\n\005Users\022\036\n\004user\030\001 \003(\0132\020.springboot." +
      "User\"\216\001\n\004User\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022" +
      "\020\n\010userName\030\003 \001(\t\022\014\n\004city\030\004 \001(\t\022\023\n\013descr" +
      "iption\030\005 \001(\t\022\025\n\rdateOfJoining\030\006 \001(\t\022\020\n\010e" +
      "xactDob\030\007 \001(\t\022\016\n\006status\030\010 \001(\005B>\n%com.jav" +
      "a.springboot.entities.protobufB\025Protocol" +
      "BufferWrapperb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_springboot_Users_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_springboot_Users_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_springboot_Users_descriptor,
        new java.lang.String[] { "User", });
    internal_static_springboot_User_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_springboot_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_springboot_User_descriptor,
        new java.lang.String[] { "Id", "Name", "UserName", "City", "Description", "DateOfJoining", "ExactDob", "Status", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
